export const SET_PIZZAS = 'PIZZA/SET_PIZZAS';
export const SET_CATEGORY = 'FILTERS/SET_CATEGORY';
export const SET_SORT_TYPE = 'FILTERS/SET_SORT_TYPE';
export const SET_ISLOADED = 'PIZZA/SET_ISLOADED';
export const ADD_PIZZA_TO_CART = 'CART/ADD_PIZZA_TO_CART';
export const CLEAR_CART = 'CART/CLEAR_CART';
export const REMOVE_ITEM_FROM_CART = 'CART/REMOVE_ITEM_FROM_CART';
export const PLUS_PIZZA_ITEM = 'CART/PLUS_PIZZA_ITEM';
export const MINUS_PIZZA_ITEM = 'CART/MINUS_PIZZA_ITEM';



